### ISSUE TITLE
two less teeth

### ISSUE THREAD

**Issue by jschoch** [Tomato1107/Cycloidal-Drive-Animation#2]
have you tried 2 less teeth?  They have some benefits.

**Comment by Tomato1107** [comment]
Not yet

**Comment by Tomato1107** [comment]
> have you tried 2 less teeth? They have some benefits.

2 less teeth is easier to draw from 3d software using two normal 1 less teeth cycloidal discs.
You can check the demo_17.py for 2 less teeth.
